import type { Meeting } from '@/types';

function escapeHtml(value?: string | number | null) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function richTextHtml(value?: string) {
  if (!value) return '<p>작성된 회의 내용이 없습니다.</p>';
  if (/<[a-z][\s\S]*>/i.test(value)) return value;
  return `<p>${escapeHtml(value).replace(/\n/g, '<br />')}</p>`;
}

function formatDate(value: string) {
  return new Date(value).toLocaleString('ko-KR', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    weekday: 'short',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function safeFileName(value: string) {
  return value
    .replace(/[\\/:*?"<>|]/g, '')
    .replace(/\s+/g, '_')
    .slice(0, 80);
}

function renderInfo(label: string, value?: string | number | null) {
  if (!value) return '';
  return `
    <div class="info-item">
      <dt>${escapeHtml(label)}</dt>
      <dd>${escapeHtml(value)}</dd>
    </div>
  `;
}

function renderList(title: string, items?: string[]) {
  const filteredItems = items?.filter(Boolean) || [];
  if (filteredItems.length === 0) return '';

  return `
    <section>
      <h2>${escapeHtml(title)}</h2>
      <ul>
        ${filteredItems.map((item) => `<li>${escapeHtml(item)}</li>`).join('')}
      </ul>
    </section>
  `;
}

function buildMeetingPdfHtml(meeting: Meeting) {
  const attendeeNames = meeting.attendees?.map((attendee) => attendee.member?.name).filter(Boolean) || [];
  const agendaItems = meeting.agendas?.map((agenda) => {
    return `${agenda.title}${agenda.description ? ` - ${agenda.description}` : ''}`;
  });
  const actionItems = meeting.actionItems?.map((item) => {
    const assignee = item.assignee?.name ? ` / 담당: ${item.assignee.name}` : '';
    const due = item.dueDate ? ` / 마감: ${new Date(item.dueDate).toLocaleDateString('ko-KR')}` : '';
    return `${item.title}${assignee}${due}`;
  });

  return `
    <article class="meeting-pdf">
      <header>
        <p class="eyebrow">INTRUTH 회의자료</p>
        <h1>${escapeHtml(meeting.title)}</h1>
        <dl>
          ${renderInfo('일시', formatDate(meeting.meetingDate))}
          ${renderInfo('팀', meeting.team?.name)}
          ${renderInfo('프로젝트', meeting.project?.name)}
          ${renderInfo('작성자', meeting.author?.name)}
        </dl>
      </header>

      ${renderList('참석자', attendeeNames)}

      <section>
        <h2>회의 내용</h2>
        <div class="content">${richTextHtml(meeting.content)}</div>
      </section>

      ${
        meeting.summary
          ? `<section><h2>결정사항 / 요약</h2><div class="summary">${richTextHtml(meeting.summary)}</div></section>`
          : ''
      }

      ${renderList('안건', agendaItems)}
      ${renderList('액션 아이템', actionItems)}

      <footer>
        <span>Generated by INTRUTH</span>
        <span>${new Date().toLocaleDateString('ko-KR')}</span>
      </footer>
    </article>
  `;
}

function createPdfContainer(meeting: Meeting) {
  const container = document.createElement('div');
  container.style.position = 'fixed';
  container.style.left = '-10000px';
  container.style.top = '0';
  container.style.width = '794px';
  container.style.background = '#ffffff';
  container.style.color = '#151515';
  container.innerHTML = `
    <style>
      .meeting-pdf {
        box-sizing: border-box;
        width: 794px;
        min-height: 1123px;
        padding: 48px;
        background: #ffffff;
        color: #171717;
        font-family: -apple-system, BlinkMacSystemFont, "Pretendard", "Noto Sans KR", "Malgun Gothic", sans-serif;
      }
      .meeting-pdf header {
        border-bottom: 3px solid #00bcd4;
        padding-bottom: 28px;
        margin-bottom: 28px;
      }
      .meeting-pdf .eyebrow {
        margin: 0 0 10px;
        color: #00838f;
        font-size: 14px;
        font-weight: 700;
      }
      .meeting-pdf h1 {
        margin: 0 0 22px;
        font-size: 34px;
        line-height: 1.25;
        letter-spacing: 0;
      }
      .meeting-pdf h2 {
        margin: 0 0 14px;
        font-size: 19px;
        line-height: 1.35;
      }
      .meeting-pdf section {
        margin: 0 0 28px;
      }
      .meeting-pdf dl {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 12px;
        margin: 0;
      }
      .meeting-pdf .info-item {
        border: 1px solid #e5e7eb;
        border-radius: 8px;
        padding: 12px 14px;
      }
      .meeting-pdf dt {
        color: #6b7280;
        font-size: 12px;
        margin-bottom: 6px;
      }
      .meeting-pdf dd {
        margin: 0;
        font-size: 15px;
        font-weight: 650;
      }
      .meeting-pdf .content,
      .meeting-pdf .summary {
        border: 1px solid #e5e7eb;
        border-radius: 8px;
        padding: 18px;
        font-size: 15px;
        line-height: 1.75;
      }
      .meeting-pdf .summary {
        background: #effdff;
        border-color: #b2ebf2;
      }
      .meeting-pdf p {
        margin: 0 0 10px;
      }
      .meeting-pdf ul {
        margin: 0;
        padding: 0;
        list-style: none;
        display: grid;
        gap: 8px;
      }
      .meeting-pdf li {
        border: 1px solid #e5e7eb;
        border-radius: 8px;
        padding: 11px 13px;
        line-height: 1.55;
      }
      .meeting-pdf footer {
        display: flex;
        justify-content: space-between;
        border-top: 1px solid #e5e7eb;
        color: #6b7280;
        font-size: 12px;
        margin-top: 40px;
        padding-top: 16px;
      }
    </style>
    ${buildMeetingPdfHtml(meeting)}
  `;
  return container;
}

export async function generateMeetingPdfFile(meeting: Meeting) {
  const [{ default: html2canvas }, { jsPDF }] = await Promise.all([
    import('html2canvas'),
    import('jspdf'),
  ]);
  const container = createPdfContainer(meeting);
  document.body.appendChild(container);

  try {
    await document.fonts?.ready;
    await new Promise((resolve) => requestAnimationFrame(resolve));

    const canvas = await html2canvas(container, {
      backgroundColor: '#ffffff',
      scale: Math.min(window.devicePixelRatio || 2, 2),
      useCORS: true,
      windowWidth: 794,
    });

    const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const pageWidth = 210;
    const pageHeight = 297;
    const margin = 10;
    const imageWidth = pageWidth - margin * 2;
    const imageHeight = (canvas.height * imageWidth) / canvas.width;
    const imageData = canvas.toDataURL('image/png');

    let heightLeft = imageHeight;
    let y = margin;

    pdf.addImage(imageData, 'PNG', margin, y, imageWidth, imageHeight);
    heightLeft -= pageHeight - margin * 2;

    while (heightLeft > 0) {
      pdf.addPage();
      y = margin - (imageHeight - heightLeft);
      pdf.addImage(imageData, 'PNG', margin, y, imageWidth, imageHeight);
      heightLeft -= pageHeight - margin * 2;
    }

    const blob = pdf.output('blob');
    const fileName = `${safeFileName(meeting.title || 'meeting')}.pdf`;
    return new File([blob], fileName, { type: 'application/pdf' });
  } finally {
    document.body.removeChild(container);
  }
}
